#moves to the directory the user was in when they ran qsub
cd ${SLURM_SUBMIT_DIR} #assumed to be the source tree

#check that the script was submit from the right place.
if [ -d "./includes" ] && [ -d "./libs" ] && [ -d "./scripts" ] && [ -d "./src" ]
then
	echo "Ran from the correct directory. Continuing with the execution."
else
	echo "ERROR: Not ran from the right place! Plase submit from the root of your repository."
	exit 1
fi

# check that the scirpt was run in a singularity shell
raxmlexists=$(command -v raxmlHPC)
if [[ $raxmlexists == "/usr/bin/raxmlHPC" ]]
then
    echo "RAxML exists so assuming that the the script was run in a singularity shell."
else
    echo "ERROR: RAxML binary does not exist. Make sure that the script is run inside a singularity shell."
    exit 1
fi

#build the programs and output the stdout to logs in scratch
LOG_FILE="/scratch/users/minhyuk2/logs/mission-control-$(date +"%Y_%m_%d_%I_%M_%p").log"
${SLURM_SUBMIT_DIR}/scripts/build_and_compile.sh && ${SLURM_SUBMIT_DIR}/build/bin/mission-control > $LOG_FILE

# move the output log to logs
echo "End Program Output" >> $LOG_FILE
echo "------------------" >> $LOG_FILE
echo "Begin Cluster Log" >> $LOG_FILE
cat ${SLURM_SUBMIT_DIR}/slurm* >> $LOG_FILE && rm ${SLURM_SUBMIT_DIR}/slurm*

echo "Ran to completion" >> $LOG_FILE
cat $LOG_FILE >> "${SLURM_SUBMIT_DIR}/run.log"
