#!/bin/bash
#PBS -A bbaz
#PBS -j oe
#PBS -l nodes=1:ppn=32:xe
#PBS -l walltime=16:00:00
#PBS -l gres=shifter
#PBS -v UDI=minpark815/bio:latest
#PBS -q normal
#PBS -N MissionControl

export CRAY_ROOTFS=SHIFTER
module load shifter

cd $PBS_O_WORKDIR

if [ -f aprun.log ]; then
    mv aprun.log aprun.old.log
fi

aprun -b -N 1 -cc none -- $PBS_O_WORKDIR/scripts/batch_script.aprun > $PBS_O_WORKDIR/aprun.log
